root = "."
tmp_dir = "tmp"

[build]
bin = "main"                   # Updated path to the binary
cmd = "go build main.go" # Updated command to build the binary
include_ext = ["go"]               # File extensions to watch
exclude_dir = ["assets", "tmp"]    # Directories to exclude from watching

[watch]
include = ["**/*.go"] # Files to watch for changes
exclude = ["tmp/**"]  # Exclude the tmp directory

[color]
main = "yellow"
watcher = "cyan"
build = "green"
log = "white"
